version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'monday'
    open-pull-requests-limit: 10
    reviewers:
      - 'kubemq-io/sdk-maintainers'
    labels:
      - 'dependencies'
    groups:
      production:
        dependency-type: 'production'
        update-types:
          - 'minor'
          - 'patch'
      dev:
        dependency-type: 'development'
        update-types:
          - 'minor'
          - 'patch'
    ignore:
      - dependency-name: '@grpc/grpc-js'
        update-types: ['version-update:semver-major']

  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'monday'
    labels:
      - 'ci'
